# Generated by Django 4.2.9 on 2024-01-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('types', models.CharField(choices=[('director', 'Director'), ('writer', 'Writer'), ('actor', 'Actor')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
                ('poster', models.FileField(upload_to='posters/')),
                ('bg_picture', models.FileField(upload_to='backgrounds/')),
                ('release_year', models.IntegerField()),
                ('mpa_rating', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=5)),
                ('imdb_rating', models.FloatField()),
                ('duration', models.IntegerField()),
                ('directors', models.ManyToManyField(related_name='directed_movies', to='movies.person')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('stars', models.ManyToManyField(related_name='starred_movies', to='movies.person')),
                ('writers', models.ManyToManyField(related_name='written_movies', to='movies.person')),
            ],
        ),
    ]
